### ISSUE TITLE
Either hide or change icon for R1_S4_HIVESHIP_ORBS 

### ISSUE THREAD

**Issue by delphiactual** [ArkahnX/DestinyLootHistory#41]
This is the faction that represents Calcified Fragments

**Comment by ArkahnX** [comment]
Thanks for the catch! This will be on the next release, showing this icon https://www.bungie.net/en/Armory/Detail?item=1069694698&itemname=Calcified%20Fragment

**Comment by ArkahnX** [comment]
Closed with #43
