### ISSUE TITLE
[FR] Option between absolute and relative dates

### ISSUE THREAD

**Issue by delphiactual** [ArkahnX/DestinyLootHistory#56]
Instead of only showing 8 days ago it would be great to be able to see the exact date and time of the History...

**Comment by ArkahnX** [comment]
If you hover over the time it will give you an exact timestamp, but I'll add that toggle in the next release

**Comment by ArkahnX** [comment]
Option added with commit 3194872a8f1f895ead45d57d7df071aa15b5f2ee

Will be released soonish?
