### ISSUE TITLE
Daily/Weekly Graph of Gains

### ISSUE THREAD

**Issue by delphiactual** [ArkahnX/DestinyLootHistory#68]
Add a page where I can check my productivity per character at a glance...

**Comment by ArkahnX** [comment]
What kind of productivity are you thinking?

I could look up currency earned /spent, three of coins used per exotic, activities entered (I don't track completion of activities)

Maybe time spent in PvP vs pve, anything else?

**Comment by delphiactual** [comment]
All that sounds wonderful, xp/glimmer/rep earned

**Comment by ArkahnX** [comment]
Alright no promises until after rise of iron, after work this weekend my top priority is making sure all of the fancy new things in rise of iron don't explode the app.

**Comment by delphiactual** [comment]
understandable

**Comment by ArkahnX** [comment]
1.4.5 is currently uploading, when that is online you can visit "productivity.html" to see the current state of this feature.

Tentative release date is saturday.
