### ISSUE TITLE
Header Titles not lined up correctly...

### ISSUE THREAD

**Issue by delphiactual** [ArkahnX/DestinyLootHistory#75]
![screenshot 2016-09-27 02 13 12](https://cloud.githubusercontent.com/assets/4798491/18865719/edf39f2c-8459-11e6-9df3-130b44d1d7e4.png)

**Comment by ArkahnX** [comment]
Thanks for the reminder, been tweaking some of the styles, but it's still not perfect

**Comment by ArkahnX** [comment]
I have fixed the styling on the main page, but I now need to reflow all of the other pages. Will take a little longer to get this fix out.

**Comment by ArkahnX** [comment]
1.4.5 fixes this and other styling issues
