### ISSUE TITLE
Weapon Damage Type Highlights reversed in Transfer Column

### ISSUE THREAD

**Issue by delphiactual** [ArkahnX/DestinyLootHistory#77]
![screenshot 2016-10-03 00 33 37](https://cloud.githubusercontent.com/assets/4798491/19029216/6dbaf9fc-8901-11e6-81bf-c8d7ae624eda.png)

**Comment by ArkahnX** [comment]
This is actually a feature, but I've been on edge with it for a while, so I have just undone the CSS. The change will be live on the next release.
